# Generated by Django 6.1 on 2026-08-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='status',
        ),
    ]
