# Generated by Django 6.1 on 2026-08-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_remove_expense_amount_expense_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='miscellaneous',
        ),
        migrations.AddField(
            model_name='expense',
            name='miscellaneous_1',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='miscellaneous_2',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
