# Generated by Django 6.1 on 2026-08-30 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_alter_receipt_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='file',
            field=models.FileField(upload_to='receipts/%Y/%m/'),
        ),
    ]
